update install + ansible collection installation methods
cjnovak98/ocp4-disconnected-config pull request #19
Opened 2024-11-18 21:18 UTC by mriensch

updated instructions for installation/automation

2024-11-18 22:08 UTC, steve-dill approved these changes
lgtm

2024-11-19 11:51 UTC, cjnovak98 requested changes
Looks very good. Just minor tweaks could be made.

2024-11-19 11:51 UTC, cjnovak98 commented on Install.md
> + **NOTE:** This will install need the media to be mounted, and the group bars set.
Minor spelling errors. "bars" instead of "vars", and the initial sentence has some grammar that could be corrected.

Also, it might be a good idea to provide the names of the vars that will need to change, with an example?

2024-11-19 11:51 UTC, cjnovak98 commented on Install.md
>  You can get your pull secret from [https://console.redhat.com/openshift/create/local](https://console.redhat.com/openshift/create/local) and store it in `~/.docker/config` of the host where you're ru
Might also be good to put this before you run gather-content, since it is a pre-requisite to this.

2024-11-19 13:40 UTC, mriensch commented
@cjnovak98 fixed

2024-11-19 18:38 UTC, christophermay07 commented on Install.md
> +  > **NOTE:** If The goal is to have a fips enabled cluster, the bastion host also has to FIPS aswell. If you dont need fips, you can ignore the following configurations.
```suggestion
  > **NOTE:** If the goal is to have a FIPS-enabled cluster, the bastion host has to be FIPS-enabled as well. If you don't need FIPS, you can ignore the following configurations.
```

2024-11-19 18:39 UTC, christophermay07 commented on Install.md
> +**NOTE:** This will install [disconnected-collection](https://github.com/cjnovak98/ocp4-disconnected-collection) and should be run an a fresh system, when nothing else has been ran
```suggestion
**NOTE:** This will install [disconnected-collection](https://github.com/cjnovak98/ocp4-disconnected-collection) and should be run on a fresh system, before anything else has been run.
```

2024-11-19 18:40 UTC, christophermay07 commented on Install.md
> +**NOTE:** Ensure A Valid Pull-Secret Exists. You can get your pull secret from [https://console.redhat.com/openshift/create/local](https://console.redhat.com/openshift/create/local) and store it in `
```suggestion
**NOTE:** Ensure a valid pull secret exists. You can get your pull secret from [https://console.redhat.com/openshift/create/local](https://console.redhat.com/openshift/create/local) and store it in `~/.docker/config` on the host where you're running the automation. 
```

2024-11-19 18:40 UTC, christophermay07 commented on Install.md
> +Install Required Ansible Collection from the previous step:
```suggestion
Install required Ansible Collection from the previous step: 
```

2024-11-19 18:41 UTC, christophermay07 commented on Install.md
> +### Install the collection on a Disconnected machine
```suggestion
### Install the Collection on a Disconnected Machine
```

2024-11-20 15:14 UTC, merged